### ISSUE TITLE
Textadept 9.5 beta: core/lfs_ext.lua: "attempt to compare number with string"

### ISSUE THREAD

**Issue by lbmn** [xomachine/textadept-nim#2] opened 2017-07-29 04:05 UTC
I get the following error with `Textadept 9.5 beta` on Ubuntu 17.04:

> /opt/textadept/core/lfs_ext.lua:97: attempt to compare number with string

It occurs whenever opening a .nim file or pressing Ctrl-Space, etc.

This is my first time trying Textadept, so I apologize if this is a simple Textadept issue.  I tried it specifically because I came across this Nim plugin.  I am very much hoping for a lighter and more portable alternative to vscode with full Nim support.  Thank you very much for your efforts!  :+1:

**Comment by xomachine** [comment] 2017-08-06 15:28
Thank you for the report! This issue lies in lack of backward compatibility between textadept versions. Please check if it is fixed now.

**Comment by xomachine** [comment] 2017-10-31 18:53
Well I am closing the issue due to no response. I can not reproduce it after the fix, so it may be considered as fixed.

**Closed as completed by xomachine** 2017-10-31 18:53 UTC
